
-- Filter object type
IF @OBJECT_TYPE IN ('2', '4', '17', '15') -- BP, Items, Orders, Deliveries
BEGIN

DECLARE @TIMESTAMP INT
DECLARE @EXPIRED INT
DECLARE @STARTDATE DATE = '2017-06-01' -- 배포일?
DECLARE @KEY NVARCHAR(30)

SET @TIMESTAMP = DATEDIFF(SECOND, @STARTDATE, GETDATE())
SET @EXPIRED = DATEDIFF(SECOND, @STARTDATE, DATEADD(DAY, -7, GETDATE()))
SET @KEY = CAST(@LIST_OF_COLS_VAL_TAB_DEL AS NVARCHAR(30));

-- clean up old records, expired or same key/object
DELETE FROM [@SAPHOWMUCH_CHANGETRACKER] WHERE ([U_SHM_CT_Key] = @key AND [U_SHM_CT_Obj] = CAST(@OBJECT_TYPE AS NVARCHAR(30))) OR CAST([Code] AS INT) < @EXPIRED

-- since [Code] is unique key, we have to ensure its unique
WHILE EXISTS (SELECT 1 FROM [@SAPHOWMUCH_CHANGETRACKER] WHERE [Code] = @TIMESTAMP)
BEGIN
	SET @TIMESTAMP = @TIMESTAMP + 1
END

INSERT INTO [@SAPHOWMUCH_CHANGETRACKER]
VALUES (@TIMESTAMP, @TIMESTAMP, @KEY, CAST(@OBJECT_TYPE AS NVARCHAR(30)))

END
